node_exporter_enabled: true
access_list:
  groups:
    - name: lb
      ports:
        - 6443
    - name: worker
      ports:
        - 32500 # Ingress-controller
        - 32501 # Ingress-controller
        # - 30000
        # - 30002
        - 30003
        - 30005
        - 30012
        - 30013
        - 30018
        - 30019
        - 30020
        - 30024
        - 30029
        - 30031
        # - 30601
        # - 30602
        - 30603
        - 30604
        - 30652
        - 30700
        - 30701
        - 30809
        - 30810
        - 32001 # Minio
        - 32002 # Minio
        - 32007
        - 32008
        - 32009
        - 32010
        - 32011
        - 32012
        - 32013
        - 32014
        - 32015
        - 32016
        - 32017
    - name: keycloak
      ports:
        - 8443
  singles:
    - name: gitops.asax.ir
      ports:
        - 443
    - name: repo.asax.ir
      ports:
        - 80
        - 443
    - name: azure.asax.ir
      ports:
        - 80
        - 443
    - name: 172.20.29.92 # bs-kube-lbvip
      ports:
        - 6443
    - name: 172.20.29.93 # bs-kube-lbvip
      ports:
        - 6443
    - name: 172.20.29.94 # bs-kube-lbvip
      ports:
        - 6443
