node_exporter_enabled: true
access_list:
  groups:
    - name: master
      ports:
        - 6443
  singles:
    - name: gitops.asax.ir
      ports:
        - 443
    - name: repo.asax.ir
      ports:
        - 80
        - 443
    - name: azure.asax.ir
      ports:
        - 80
        - 443
