access_list:
  groups:
    - name: lb
      ports:
        - 6443
    - name: worker
      ports:
        - 8443
        - 8933
        - 10250
        # - 4789/UDP
    - name: gitlab
      ports:
        - 443
  singles:
    - name: gitops.asax.ir
      ports:
        - 443
    - name: repo.asax.ir
      ports:
        - 80
        - 443
    - name: azure.asax.ir
      ports:
        - 80
        - 443
    - name: 172.20.29.92 # bs-kube-lbvip
      ports:
        - 6443
    - name: 172.20.29.93 # bs-kube-lbvip
      ports:
        - 6443
    - name: 172.20.29.94 # bs-kube-lbvip
      ports:
        - 6443
